apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: cloud-zipkin-ui
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        name: cloud-zipkin-ui
    spec: 
      containers: 
        - name: cloud-zipkin-ui 
          image: zipkin:1.0.0 
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 9012
---
apiVersion: v1 
kind: Service
metadata: 
  name: cloud-zipkin-ui
spec: 
  ports: 
    - port: 9012
      targetPort: 9012
      protocol: TCP 
  selector: 
    name: cloud-zipkin-ui
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-zipkin-ui
spec:
  rules:
  - host: zipkin.linux100.cc
    http:
      paths:
      - backend:
          serviceName: cloud-zipkin-ui
          servicePort: 9012
