apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: cloud-config-server
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        name: cloud-config-server 
    spec: 
      containers: 
        - name: cloud-config-server 
          image: config:1.0.0 
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 1111
---
apiVersion: v1 
kind: Service
metadata: 
  name: cloud-config-server
spec: 
  ports: 
    - port: 1111
      targetPort: 1111
      protocol: TCP 
  selector: 
    name: cloud-config-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-config-server
spec:
  rules:
  - host: config.linux100.cc
    http:
      paths:
      - backend:
          serviceName: cloud-config-server
          servicePort: 1111
