apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: cloud-simple
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        name: cloud-simple
    spec: 
      containers: 
        - name: cloud-simple 
          image: simple:1.0.0 
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8081
---
apiVersion: v1 
kind: Service
metadata: 
  name: cloud-simple
spec: 
  ports: 
    - port: 8081
      targetPort: 8081
      protocol: TCP 
  selector: 
    name: cloud-simple
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud-simple
spec:
  rules:
  - host: simple.linux100.cc
    http:
      paths:
      - backend:
          serviceName: cloud-simple
          servicePort: 8081
